server:
  port: 9091

spring:
  profiles:
    active: dev

  application:
    name: RESTAURANT-SERVICE
  datasource:
    url: jdbc:mysql://mysql-db.cf888ioo64ez.us-east-1.rds.amazonaws.com:3306/restaurantdb
    password: codedecode
    username: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect